///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace postgres
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the postgresRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d6385aa8-0198-4a35-ae67-0763b5a23808")]
    public partial class postgresRepository : RepoGenBaseFolder
    {
        static postgresRepository instance = new postgresRepository();

        /// <summary>
        /// Gets the singleton class instance representing the postgresRepository element repository.
        /// </summary>
        [RepositoryFolder("d6385aa8-0198-4a35-ae67-0763b5a23808")]
        public static postgresRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public postgresRepository() 
            : base("postgresRepository", "/", null, 0, false, "d6385aa8-0198-4a35-ae67-0763b5a23808", ".\\RepositoryImages\\postgresRepositoryd6385aa8.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d6385aa8-0198-4a35-ae67-0763b5a23808")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class postgresRepositoryFolders
    {
    }
#pragma warning restore 0436
}
