///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest.ocr
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The get_string_from_ocr recording.
    /// </summary>
    [TestModule("c52d1b15-97b2-4978-aff0-477d872775e7", ModuleType.Recording, 1)]
    public partial class get_string_from_ocr : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MyTest.MyTestRepository repository.
        /// </summary>
        public static global::MyTest.MyTestRepository repo = global::MyTest.MyTestRepository.Instance;

        static get_string_from_ocr instance = new get_string_from_ocr();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public get_string_from_ocr()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static get_string_from_ocr Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            start_SUT();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Form1.timestamps'.", repo.Form1.timestampsInfo, new RecordItemIndex(1));
            repo.Form1.timestamps.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'Form1.timestamps'.", repo.Form1.timestampsInfo, new RecordItemIndex(2));
            repo.Form1.timestamps.Focus();
            Delay.Milliseconds(0);
            
            ocr_element(repo.Form1.timestampsInfo);
            Delay.Milliseconds(0);
            
            stop_SUT();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
